// =================================================
// Autogenerated from Unify 3.0.5, do not edit directly.
// =================================================

import 'package:flutter/services.dart';

import 'location_info_model.dart';

/// Call flow direction : native -> dart
abstract class LocationInfoService {

    void updateLocationInfo(LocationInfoModel model);

    int test(bool st);

    bool test2(double st);

    String test3(int st);

    int? test4(int st);

    Future<int> test5(Map<String, int> st);

    static void setup(LocationInfoService impl) {
        {
            const BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>('com.didi.flutter.uni_api.LocationInfoService.updateLocationInfo', StandardMessageCodec());
            channel.setMessageHandler((Object? message) async {
                if (message == null) return null;
                Map<Object?, Object?> wrapped = message as Map<Object?, Object?>;
                impl.updateLocationInfo(LocationInfoModel.decode(wrapped['model']!));
            });
        }
        {
            const BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>('com.didi.flutter.uni_api.LocationInfoService.test', StandardMessageCodec());
            channel.setMessageHandler((Object? message) async {
                if (message == null) return null;
                Map<Object?, Object?> wrapped = message as Map<Object?, Object?>;
                var implResult = impl.test(wrapped['st'] as bool);
                return implResult as int;
            });
        }
        {
            const BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>('com.didi.flutter.uni_api.LocationInfoService.test2', StandardMessageCodec());
            channel.setMessageHandler((Object? message) async {
                if (message == null) return null;
                Map<Object?, Object?> wrapped = message as Map<Object?, Object?>;
                var implResult = impl.test2(wrapped['st'] as double);
                return implResult as bool;
            });
        }
        {
            const BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>('com.didi.flutter.uni_api.LocationInfoService.test3', StandardMessageCodec());
            channel.setMessageHandler((Object? message) async {
                if (message == null) return null;
                Map<Object?, Object?> wrapped = message as Map<Object?, Object?>;
                var implResult = impl.test3(wrapped['st'] as int);
                return implResult as String;
            });
        }
        {
            const BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>('com.didi.flutter.uni_api.LocationInfoService.test4', StandardMessageCodec());
            channel.setMessageHandler((Object? message) async {
                if (message == null) return null;
                Map<Object?, Object?> wrapped = message as Map<Object?, Object?>;
                var implResult = impl.test4(wrapped['st'] as int);
                if (implResult == null ) return null;
                return implResult as int?;
            });
        }
        {
            const BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>('com.didi.flutter.uni_api.LocationInfoService.test5', StandardMessageCodec());
            channel.setMessageHandler((Object? message) async {
                if (message == null) return null;
                Map<Object?, Object?> wrapped = message as Map<Object?, Object?>;
                var implResult = await impl.test5((wrapped['st'] as Map).map((key, value) => MapEntry(key as String, value as int)));
                return implResult as int;
            });
        }
    }
}
