// =================================================
// Autogenerated from Unify 3.0.6, do not edit directly.
// =================================================

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN
@protocol FlutterBinaryMessenger;
@class LocationInfoModel;
typedef void (^UniCompleted)(id result); // 这里result可能是nil

// Call flow direction : native -> dart
// Before using the code generated based on the "UniFlutterModule" template, you need to call the setup method to initialize it.
@interface LocationInfoService : NSObject


+ (void)setup:(id<FlutterBinaryMessenger>)binaryMessenger;
+ (void)updateLocationInfo:(LocationInfoModel*)model;
+ (void)test:(BOOL)st result:(UniCompleted)result;
+ (void)test2:(double)st result:(UniCompleted)result;
+ (void)test3:(NSInteger)st result:(UniCompleted)result;
+ (void)test4:(NSInteger)st result:(UniCompleted)result;
+ (void)test5:(NSDictionary<NSString*, NSNumber*>*)st result:(UniCompleted)result;

@end

NS_ASSUME_NONNULL_END
