// =================================================
// Autogenerated from Unify 3.0.6, do not edit directly.
// =================================================

package com.example.uninativemodule_demo;

import java.util.List;
import java.util.Map;
import java.util.HashMap;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.StandardMessageCodec;
import com.example.uninativemodule_demo.DeviceInfoModel;

/*
 Call flow direction : dart -> native
*/
public interface DeviceInfoService {

    interface Result<T> {
        void success(T result);

    }

    /*
      获取设备信息
    */
    void getDeviceInfo(Result<DeviceInfoModel> result);

    long test(boolean st);

    boolean test2(double st);

    String test3(long st);

    long test4(long st);

    void test5(Map<String, Long> st, Result<Long> result);

}
