// =================================================
// Autogenerated from Unify 3.0.5, do not edit directly.
// =================================================

package com.example.uninativemodule_demo;

import java.util.List;
import java.util.Map;
import java.util.HashMap;
import java.util.ArrayList;
import com.example.uninativemodule_demo.uniapi.UniModel;

/*
  设备信息 实体类
*/
public class DeviceInfoModel extends UniModel {
    private String osVersion; // 系统版本
    private String memory; // 内存信息
    private String plaform; // 手机型号
    private long test;
    private boolean test2;

    public String getOsVersion() { return osVersion; }

    public void setOsVersion(String osVersion) { this.osVersion = osVersion; }

    public String getMemory() { return memory; }

    public void setMemory(String memory) { this.memory = memory; }

    public String getPlaform() { return plaform; }

    public void setPlaform(String plaform) { this.plaform = plaform; }

    public long getTest() { return test; }

    public void setTest(long test) { this.test = test; }

    public boolean getTest2() { return test2; }

    public void setTest2(boolean test2) { this.test2 = test2; }


    @Override
    public Map<String, Object> toMap() {
        Map<String, Object> result = new HashMap<>();
        result.put("osVersion", osVersion);
        result.put("memory", memory);
        result.put("plaform", plaform);
        result.put("test", test);
        result.put("test2", test2);
        return result;
    }

    public static DeviceInfoModel fromMap(Map<String, Object> map) {
        DeviceInfoModel result = new DeviceInfoModel();
        result.osVersion = map.containsKey("osVersion") && map.get("osVersion") != null ? (String) map.get("osVersion") : "";
        result.memory = map.containsKey("memory") && map.get("memory") != null ? (String) map.get("memory") : "";
        result.plaform = map.containsKey("plaform") && map.get("plaform") != null ? (String) map.get("plaform") : "";
        result.test = map.containsKey("test") && map.get("test") != null ? ((Number) map.get("test")).longValue() : 0;
        result.test2 = map.containsKey("test2") && map.get("test2") != null ? (Boolean) map.get("test2") : false;
        return result;
    }

}
