// =================================================
// Autogenerated from Unify 3.0.6, do not edit directly.
// =================================================

package com.example.uninativemodule_demo;

public interface UDUniCallbackDispose {
    void disposeCallback(UDUniCallback uniCallback);
}

