// =================================================
// Autogenerated from Unify 3.0.1, do not edit directly.
// =================================================

package com.example.uninativemodule_demo;

public class UDUniCallback {
    public String callbackName;
    public UDUniCallbackDispose disposeDelegate;

    public UDUniCallback(String callbackName, UDUniCallbackDispose disposeDelegate) {
        this.callbackName = callbackName;
        this.disposeDelegate = disposeDelegate;
    }
}

