// =================================================
// Autogenerated from Unify 3.0.5, do not edit directly.
// =================================================

import 'dart:async';
import 'package:flutter/services.dart';
import 'package:flutter/foundation.dart';
import 'uniapi/uni_api.dart';

import 'device_info_model.dart';

/// Call flow direction : dart -> native
class DeviceInfoService {

    static Future<DeviceInfoModel> getDeviceInfo() async  {
        const BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?> (
            'com.didi.flutter.uni_api.DeviceInfoService.getDeviceInfo', StandardMessageCodec());
        final Map<Object?, Object?>? replyMap =
            await channel.send(null) as Map<Object?, Object?>?;
        if (replyMap == null) {
            UniApi.trackError('DeviceInfoService', 'com.didi.flutter.uni_api.DeviceInfoService.getDeviceInfo', 'Unable to establish connection on channel : "com.didi.flutter.uni_api.DeviceInfoService.getDeviceInfo" .');
            if (!kReleaseMode) {
                throw PlatformException(
                    code: 'channel-error',
                    message: 'Unable to establish connection on channel : "com.didi.flutter.uni_api.DeviceInfoService.getDeviceInfo" .',
                    details: null,
                );
            }
        } else if (replyMap['error'] != null) {
            final Map<Object?, Object?> error = (replyMap['error']  as Map<Object?, Object?>);
            String errorMsg = '';
            if (error.containsKey('code')) errorMsg += '[ ${error['code']?.toString() ?? ''} ]';
            if (error.containsKey('message')) errorMsg += '[ ${error['message']?.toString() ?? ''} ]';
            if (error.containsKey('details')) errorMsg += '[ ${error['details']?.toString() ?? ''} ]';
            UniApi.trackError('DeviceInfoService', 'com.didi.flutter.uni_api.DeviceInfoService.getDeviceInfo', 'getDeviceInfo: $errorMsg);');
            if (!kReleaseMode) {
                throw PlatformException(
                    code: error['code'] as String,
                    message: error['message'] as String,
                    details: error['details'],
                );
            }
        } else {
            return DeviceInfoModel.decode(replyMap['result']!);
        }
        throw Exception('方法 "getDeviceInfo" : 返回类型错误!');
    }

    static Future<int> test(bool st) async  {
        final Map<String, dynamic> encoded = {};
        encoded["st"] = st as bool;
        const BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?> (
            'com.didi.flutter.uni_api.DeviceInfoService.test', StandardMessageCodec());
        final Map<Object?, Object?>? replyMap =
            await channel.send(encoded) as Map<Object?, Object?>?;
        if (replyMap == null) {
            UniApi.trackError('DeviceInfoService', 'com.didi.flutter.uni_api.DeviceInfoService.test', 'Unable to establish connection on channel : "com.didi.flutter.uni_api.DeviceInfoService.test" .');
            if (!kReleaseMode) {
                throw PlatformException(
                    code: 'channel-error',
                    message: 'Unable to establish connection on channel : "com.didi.flutter.uni_api.DeviceInfoService.test" .',
                    details: null,
                );
            }
        } else if (replyMap['error'] != null) {
            final Map<Object?, Object?> error = (replyMap['error']  as Map<Object?, Object?>);
            String errorMsg = '';
            if (error.containsKey('code')) errorMsg += '[ ${error['code']?.toString() ?? ''} ]';
            if (error.containsKey('message')) errorMsg += '[ ${error['message']?.toString() ?? ''} ]';
            if (error.containsKey('details')) errorMsg += '[ ${error['details']?.toString() ?? ''} ]';
            UniApi.trackError('DeviceInfoService', 'com.didi.flutter.uni_api.DeviceInfoService.test', 'test: $errorMsg);');
            if (!kReleaseMode) {
                throw PlatformException(
                    code: error['code'] as String,
                    message: error['message'] as String,
                    details: error['details'],
                );
            }
        } else {
            return replyMap['result'] as int;
        }
        throw Exception('方法 "test" : 返回类型错误!');
    }

    static Future<bool> test2(double st) async  {
        final Map<String, dynamic> encoded = {};
        encoded["st"] = st as double;
        const BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?> (
            'com.didi.flutter.uni_api.DeviceInfoService.test2', StandardMessageCodec());
        final Map<Object?, Object?>? replyMap =
            await channel.send(encoded) as Map<Object?, Object?>?;
        if (replyMap == null) {
            UniApi.trackError('DeviceInfoService', 'com.didi.flutter.uni_api.DeviceInfoService.test2', 'Unable to establish connection on channel : "com.didi.flutter.uni_api.DeviceInfoService.test2" .');
            if (!kReleaseMode) {
                throw PlatformException(
                    code: 'channel-error',
                    message: 'Unable to establish connection on channel : "com.didi.flutter.uni_api.DeviceInfoService.test2" .',
                    details: null,
                );
            }
        } else if (replyMap['error'] != null) {
            final Map<Object?, Object?> error = (replyMap['error']  as Map<Object?, Object?>);
            String errorMsg = '';
            if (error.containsKey('code')) errorMsg += '[ ${error['code']?.toString() ?? ''} ]';
            if (error.containsKey('message')) errorMsg += '[ ${error['message']?.toString() ?? ''} ]';
            if (error.containsKey('details')) errorMsg += '[ ${error['details']?.toString() ?? ''} ]';
            UniApi.trackError('DeviceInfoService', 'com.didi.flutter.uni_api.DeviceInfoService.test2', 'test2: $errorMsg);');
            if (!kReleaseMode) {
                throw PlatformException(
                    code: error['code'] as String,
                    message: error['message'] as String,
                    details: error['details'],
                );
            }
        } else {
            return replyMap['result'] as bool;
        }
        throw Exception('方法 "test2" : 返回类型错误!');
    }

    static Future<String> test3(int st) async  {
        final Map<String, dynamic> encoded = {};
        encoded["st"] = st as int;
        const BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?> (
            'com.didi.flutter.uni_api.DeviceInfoService.test3', StandardMessageCodec());
        final Map<Object?, Object?>? replyMap =
            await channel.send(encoded) as Map<Object?, Object?>?;
        if (replyMap == null) {
            UniApi.trackError('DeviceInfoService', 'com.didi.flutter.uni_api.DeviceInfoService.test3', 'Unable to establish connection on channel : "com.didi.flutter.uni_api.DeviceInfoService.test3" .');
            if (!kReleaseMode) {
                throw PlatformException(
                    code: 'channel-error',
                    message: 'Unable to establish connection on channel : "com.didi.flutter.uni_api.DeviceInfoService.test3" .',
                    details: null,
                );
            }
        } else if (replyMap['error'] != null) {
            final Map<Object?, Object?> error = (replyMap['error']  as Map<Object?, Object?>);
            String errorMsg = '';
            if (error.containsKey('code')) errorMsg += '[ ${error['code']?.toString() ?? ''} ]';
            if (error.containsKey('message')) errorMsg += '[ ${error['message']?.toString() ?? ''} ]';
            if (error.containsKey('details')) errorMsg += '[ ${error['details']?.toString() ?? ''} ]';
            UniApi.trackError('DeviceInfoService', 'com.didi.flutter.uni_api.DeviceInfoService.test3', 'test3: $errorMsg);');
            if (!kReleaseMode) {
                throw PlatformException(
                    code: error['code'] as String,
                    message: error['message'] as String,
                    details: error['details'],
                );
            }
        } else {
            return replyMap['result'] as String;
        }
        throw Exception('方法 "test3" : 返回类型错误!');
    }

    static Future<int?> test4(int st) async  {
        final Map<String, dynamic> encoded = {};
        encoded["st"] = st as int;
        const BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?> (
            'com.didi.flutter.uni_api.DeviceInfoService.test4', StandardMessageCodec());
        final Map<Object?, Object?>? replyMap =
            await channel.send(encoded) as Map<Object?, Object?>?;
        if (replyMap == null) {
            UniApi.trackError('DeviceInfoService', 'com.didi.flutter.uni_api.DeviceInfoService.test4', 'Unable to establish connection on channel : "com.didi.flutter.uni_api.DeviceInfoService.test4" .');
            if (!kReleaseMode) {
                throw PlatformException(
                    code: 'channel-error',
                    message: 'Unable to establish connection on channel : "com.didi.flutter.uni_api.DeviceInfoService.test4" .',
                    details: null,
                );
            }
        } else if (replyMap['error'] != null) {
            final Map<Object?, Object?> error = (replyMap['error']  as Map<Object?, Object?>);
            String errorMsg = '';
            if (error.containsKey('code')) errorMsg += '[ ${error['code']?.toString() ?? ''} ]';
            if (error.containsKey('message')) errorMsg += '[ ${error['message']?.toString() ?? ''} ]';
            if (error.containsKey('details')) errorMsg += '[ ${error['details']?.toString() ?? ''} ]';
            UniApi.trackError('DeviceInfoService', 'com.didi.flutter.uni_api.DeviceInfoService.test4', 'test4: $errorMsg);');
            if (!kReleaseMode) {
                throw PlatformException(
                    code: error['code'] as String,
                    message: error['message'] as String,
                    details: error['details'],
                );
            }
        } else {
            return replyMap['result'] == null ? null : replyMap['result'] as int?;
        }
        throw Exception('方法 "test4" : 返回类型错误!');
    }

    static Future<int> test5(Map<String, int> st) async  {
        final Map<String, dynamic> encoded = {};
        encoded["st"] = st as Map<String, int>;
        const BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?> (
            'com.didi.flutter.uni_api.DeviceInfoService.test5', StandardMessageCodec());
        final Map<Object?, Object?>? replyMap =
            await channel.send(encoded) as Map<Object?, Object?>?;
        if (replyMap == null) {
            UniApi.trackError('DeviceInfoService', 'com.didi.flutter.uni_api.DeviceInfoService.test5', 'Unable to establish connection on channel : "com.didi.flutter.uni_api.DeviceInfoService.test5" .');
            if (!kReleaseMode) {
                throw PlatformException(
                    code: 'channel-error',
                    message: 'Unable to establish connection on channel : "com.didi.flutter.uni_api.DeviceInfoService.test5" .',
                    details: null,
                );
            }
        } else if (replyMap['error'] != null) {
            final Map<Object?, Object?> error = (replyMap['error']  as Map<Object?, Object?>);
            String errorMsg = '';
            if (error.containsKey('code')) errorMsg += '[ ${error['code']?.toString() ?? ''} ]';
            if (error.containsKey('message')) errorMsg += '[ ${error['message']?.toString() ?? ''} ]';
            if (error.containsKey('details')) errorMsg += '[ ${error['details']?.toString() ?? ''} ]';
            UniApi.trackError('DeviceInfoService', 'com.didi.flutter.uni_api.DeviceInfoService.test5', 'test5: $errorMsg);');
            if (!kReleaseMode) {
                throw PlatformException(
                    code: error['code'] as String,
                    message: error['message'] as String,
                    details: error['details'],
                );
            }
        } else {
            return replyMap['result'] as int;
        }
        throw Exception('方法 "test5" : 返回类型错误!');
    }

}
