// =================================================
// Autogenerated from Unify 3.0.5, do not edit directly.
// =================================================

package com.example.unifluttermodule_demo;

public interface UFUniCallbackDispose {
    void disposeCallback(UFUniCallback uniCallback);
}

